name: Enable SSH

on: push

jobs:
  enable-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH server
      run: sudo apt-get install -y openssh-server

    - name: Start SSH service
      run: sudo service ssh start

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Print SSH connection details
      run: |
        echo "Run the following command to connect via SSH:"
        echo "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p ${{ runner.port }} ${{ runner.hostname }}"
